version: '3.1'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${BEFAST_PASSWORD}
    volumes:
      - nextjs_redis_data:/data

volumes:
  nextjs_redis_data:

networks:
  default:
    name: befast-compose-shared
    external: true
