version: '3.1'

services:
  redis-isolated:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${BEFAST_PASSWORD}
    volumes:
      - nextjs_redisdata:/data

volumes:
  nextjs_redisdata:

networks:
  default:
    name: compose-shared
    external: true
