import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">home</Link>
          <br />
          <Link href="/job-processing">job-processing</Link>
          <br />
          <Link href="/job-processing/status">job-processing/status</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  )
}
